unique_ids:
  assets:
    standard-page.html: Q5XOECPA3SOF7LBPK3K67ZU2AZNSPAFH
    theme.css: OL4QFJFCMYFFVVDKTXCCG72S3HLEM3HW
  forms:
    Form1: JYI3KSZDJDL54AC5Z4OGK2KEB5W4VG4C
  modules: {}
  scripts: {}
  server_modules: {}
